version: '3.9'
services:
  metabase:
    image: metabase/metabase:v0.39.4
    container_name: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase_data:/metabase-data 
    ports:
      - 3000:3000
    environment: 
      MB_DB_FILE: /metabase-data/metabase.db
volumes:
  metabase_data:
